package FinalProject;

import java.util.ArrayList;
import java.util.List;

public class Prepositions {
    List<String> contents;
    public Prepositions(){
        contents = new ArrayList<>();
        // List provided by https://www.englishclub.com/grammar/prepositions-list.php
        contents.add("aboard");
        contents.add("about");
        contents.add("above");
        contents.add("across");
        contents.add("after");
        contents.add("against");
        contents.add("along");
        contents.add("amid");
        contents.add("among");
        contents.add("anti");
        contents.add("around");
        contents.add("as");
        contents.add("at");
        contents.add("before");
        contents.add("behind");
        contents.add("below");
        contents.add("beneath");
        contents.add("beside");
        contents.add("besides");
        contents.add("between");
        contents.add("beyond");
        contents.add("but");
        contents.add("by");
        contents.add("concerning");
        contents.add("considering");
        contents.add("despite");
        contents.add("down");
        contents.add("during");
        contents.add("except");
        contents.add("excepting");
        contents.add("excluding");
        contents.add("following");
        contents.add("for");
        contents.add("from");
        contents.add("in");
        contents.add("inside");
        contents.add("into");
        contents.add("like");
        contents.add("minus");
        contents.add("near");
        contents.add("of");
        contents.add("off");
        contents.add("on");
        contents.add("onto");
        contents.add("opposite");
        contents.add("outside");
        contents.add("over");
        contents.add("past");
        contents.add("per");
        contents.add("plus");
        contents.add("regarding");
        contents.add("round");
        contents.add("save");
        contents.add("since");
        contents.add("than");
        contents.add("through");
        contents.add("to");
        contents.add("toward");
        contents.add("towards");
        contents.add("under");
        contents.add("underneath");
        contents.add("unlike");
        contents.add("until");
        contents.add("up");
        contents.add("upon");
        contents.add("versus");
        contents.add("via");
        contents.add("with");
        contents.add("within");
        contents.add("without");
    }
}
